### PR TITLE
Replacing Makefile with Bakefile

### LINKED ISSUE #2: Port Makefile to Bakefile
`bake` is a tool for automate commands workflows.

Has a `Bakefile` and it is similar with the `Makefile` syntax.

Info:
https://github.com/kennethreitz/bake

Acceptance Criteria:
- All commands must be ported (except help, that bake do it for us)

### PR DESCRIPTION
**Pull request by armonge**
Fixes #2

### CODE REVIEW

**Comment by dutradda** [comment]
@armonge Thank you for the PR!

Can you add bake on dev requirements at [pyproject.toml](https://github.com/dutradda/apidaora/blob/master/pyproject.toml#L27)?

**Comment by cesarbruschetta** [comment]
@dutradda @armonge 
I believe the jo project runs on python 3.8 I think we should fix this when creating make file

And I also think we should add in `README.md` or `docs` base system dependencies, such as `bake-cli, Cargo, the Rust package manager`, or other basic project needs.

**Comment by dutradda** [comment]
@cesarbruschetta 

We really need a CONTRIBUTING.md file!

I don't understand your point about python3.8 and makefile

**Comment by cesarbruschetta** [comment]
> I don't understand your point about python3.8 and makefile

My point is that the `virtualenv ` created by `makefile`  is `python3.7` the correct would not be `python3.8` ?

**Comment by dutradda** [comment]
@armonge I already do this task

I am sorry but I will close your PR

**Comment by armonge** [comment]
Hi @dutradda no worries, sorry i was unavailable last week

**Pull request closed without merging**
